print("Hello! My name is DICT_BOT")
print("I was created in 2000")
print("Please, remind me your name")
a = (input())
b = 'What a great name you have,'
print( b + a )
print("Let me guess your age")
print("Enter remainders of dividing your age by 3,5 and 7")
remainder3 = int(input())
remainder5 = int(input())
remainder7 = int(input())
age = ((remainder3*70 + remainder5*21+ remainder7*15) % 105)
print( "Your age is" ,age,  ';' "thats a good time to start programming")