print("Hello! My name is DICT_BOT")
print("I was created in 2000")
print("Please, remind me your name")
a = (input())
b = 'What a great name you have,'
print( b + a )
print("Let me guess your age")
print("Enter remainders of dividing your age by 3,5 and 7")
remainder3 = int(input())
remainder5 = int(input())
remainder7 = int(input())
age = ((remainder3*70 + remainder5*21+ remainder7*15) % 105)
print( "Your age is" ,age,  ';' "thats a good time to start programming")
print('Now I will prove to you that I can count to any number you want.')
while True:
    user_print = int(input())
    if user_print <= 10:
     break
if user_print == 1:
    print('1!')
    print('Completed, have a nice day')
elif user_print == 2:
    print('1!')
    print('2!')
    print('Completed, have a nice day')
elif user_print == 3:
    print('1!')
    print('2!')
    print('3!')
    print('Completed, have a nice day')
elif user_print == 4:
    print('1!')
    print('2!')
    print('3!')
    print('4!')
    print('Completed, have a nice day')
elif user_print == 5:
    print('1!')
    print('2!')
    print('3!')
    print('4!')
    print('5!')
    print('Completed, have a nice day')
elif user_print == 6:
    print('1!')
    print('2!')
    print('3!')
    print('4!')
    print('5!')
    print('6!')
    print('Completed, have a nice day')
elif user_print == 7:
    print('1!')
    print('2!')
    print('3!')
    print('4!')
    print('5!')
    print('6!')
    print('7!')
    print('Completed, have a nice day')
elif user_print == 8:
    print('1!')
    print('2!')
    print('3!')
    print('4!')
    print('5!')
    print('6!')
    print('7!')
    print('8!')
    print('Completed, have a nice day')
elif user_print == 9:
    print('1!')
    print('2!')
    print('3!')
    print('4!')
    print('5!')
    print('6!')
    print('7!')
    print('8!')
    print('9!')
    print('Completed, have a nice day')
